### ISSUE TITLE
GetRoles

### ISSUE THREAD

**Issue by gomarcel** [IUNO-TDM/OAuth2Server#10]
GetRoles must be implemented

**Comment by MBeuttler** [comment]
@gomarcel What't that ticket about?

**Comment by bockha** [comment]
What is a role? Can we try to develop with permissions instead of roles?

**Comment by gomarcel** [comment]
1) The Administrator needs to be able to change/update/insert User Roles. Therefore a database function is needed. 
2) Permissions defines what a role might do. Ever User is attached to at least one role. A role has permissions to use database functions. See https://github.com/IUNO-TDM/MarketplaceCore/blob/master/SqlScripts/ROLES_AND_PERMISSIONS.md and https://github.com/IUNO-TDM/OAuth2Server/blob/master/ROLES_SCOPES_PERMISSIONS.md

**Comment by gomarcel** [comment]
Changed Milestone - Not needed to EMO
