### ISSUE TITLE
SetPayment Call

### ISSUE THREAD

**Issue by gomarcel** [IUNO-TDM/OAuth2Server#11]
At the moment the SetPayment DB Function can be called only with the Role "MarketplaceComponent". There is no differentiation on UserUUID. This might be a secury issue and should be reviewed.

**Comment by bockha** [comment]
@gomarcel please provide the necessary documents and figures for the review and schedule a review meeting.

**Comment by MBeuttler** [comment]
We did change this behaviour. Know only the marketplace core itself can call this function. Therefore we created a new user and role that is only applied to the core self.

**Comment by gomarcel** [comment]
Can we close the issue???
