### ISSUE TITLE
which hash algorithm is used to secure stored passwords

### ISSUE THREAD

**Issue by bockha** [IUNO-TDM/OAuth2Server#25]
Please tell me, which algorithm is used to secure user passwords stored in the database. [This article](https://www.heise.de/security/meldung/Finger-weg-von-SHA-1-320-Millionen-Passwoerter-geknackt-3822005.html) states, that _bcrypt_ or _pbkdf2_ shall be used.

**Comment by MBeuttler** [comment]
Algorithm | Max password length | Adaptive? | Salt bits | Description
bf | 72 | yes | 128 | Blowfish-based, variant 2a

**Comment by MBeuttler** [comment]
https://www.postgresql.org/docs/8.3/static/pgcrypto.html
